-- =====================================================================
-- 004_seed_municipios_zonas.sql
--
-- Os 223 municípios da Paraíba e suas zonas eleitorais.
--
-- Fonte: "Todos os Municípios da Paraíba — Zona, Advogado e Telefone"
-- (Coordenação Jurídica da Campanha Lucas Ribeiro — Governador 2026),
-- elaborado em 07/09/2026 a partir da relação oficial do TRE-PB, com
-- checagem cruzada na planilha "Unidades Operacionais - Municípios
-- Abrangidos.xlsx" (Operação Voto Seguro 2026, PMPB). Nomes de
-- município conferidos contra a lista oficial do IBGE (223 municípios).
--
-- IMPORTANTE: "Natuba" está com zonas = NULL/vazio porque a fonte
-- consultada não localizou a zona eleitoral desse município (observação
-- expressa no documento original). Não presuma um valor — confirme com
-- o TRE-PB e atualize manualmente antes do dia da eleição:
--   update public.municipios_zonas set zonas = array['NN'] where municipio = 'Natuba';
-- =====================================================================

insert into public.municipios_zonas (municipio, zonas) values
('Água Branca', ARRAY['74']),
('Aguiar', ARRAY['66']),
('Alagoa Grande', ARRAY['9']),
('Alagoa Nova', ARRAY['13']),
('Alagoinha', ARRAY['9']),
('Alcantil', ARRAY['18']),
('Algodão de Jandaíra', ARRAY['67']),
('Alhandra', ARRAY['73']),
('Amparo', ARRAY['43']),
('Aparecida', ARRAY['63']),
('Araçagi', ARRAY['47']),
('Arara', ARRAY['48']),
('Araruna', ARRAY['20']),
('Areia', ARRAY['11']),
('Areia de Baraúnas', ARRAY['65']),
('Areial', ARRAY['19']),
('Aroeiras', ARRAY['49']),
('Assunção', ARRAY['27']),
('Baía da Traição', ARRAY['55']),
('Bananeiras', ARRAY['14']),
('Baraúna', ARRAY['25']),
('Barra de Santa Rosa', ARRAY['67']),
('Barra de Santana', ARRAY['49']),
('Barra de São Miguel', ARRAY['62']),
('Bayeux', ARRAY['61']),
('Belém', ARRAY['14']),
('Belém do Brejo do Cruz', ARRAY['38']),
('Bernardino Batista', ARRAY['53']),
('Boa Ventura', ARRAY['42']),
('Boa Vista', ARRAY['22']),
('Bom Jesus', ARRAY['68']),
('Bom Sucesso', ARRAY['36']),
('Bonito de Santa Fé', ARRAY['40']),
('Boqueirão', ARRAY['62']),
('Borborema', ARRAY['11']),
('Brejo do Cruz', ARRAY['38']),
('Brejo dos Santos', ARRAY['36']),
('Caaporã', ARRAY['73']),
('Cabaceiras', ARRAY['62']),
('Cabedelo', ARRAY['57']),
('Cachoeira dos Índios', ARRAY['68']),
('Cacimba de Areia', ARRAY['65']),
('Cacimba de Dentro', ARRAY['20']),
('Cacimbas', ARRAY['30']),
('Caiçara', ARRAY['14']),
('Cajazeiras', ARRAY['68']),
('Cajazeirinhas', ARRAY['52']),
('Caldas Brandão', ARRAY['75']),
('Camalaú', ARRAY['29']),
('Campina Grande', ARRAY['16','17','72']),
('Capim', ARRAY['7']),
('Caraúbas', ARRAY['22']),
('Carrapateira', ARRAY['40']),
('Casserengue', ARRAY['48']),
('Catingueira', ARRAY['32']),
('Catolé do Rocha', ARRAY['36']),
('Caturité', ARRAY['59']),
('Conceição', ARRAY['41']),
('Condado', ARRAY['51']),
('Conde', ARRAY['3']),
('Congo', ARRAY['43']),
('Coremas', ARRAY['52']),
('Coxixola', ARRAY['58']),
('Cruz do Espírito Santo', ARRAY['3']),
('Cubati', ARRAY['23']),
('Cuité', ARRAY['24']),
('Cuité de Mamanguape', ARRAY['7']),
('Cuitegi', ARRAY['11']),
('Curral de Cima', ARRAY['60']),
('Curral Velho', ARRAY['42']),
('Damião', ARRAY['24']),
('Desterro', ARRAY['30']),
('Diamante', ARRAY['42']),
('Dona Inês', ARRAY['14']),
('Duas Estradas', ARRAY['47']),
('Emas', ARRAY['32']),
('Esperança', ARRAY['19']),
('Fagundes', ARRAY['59']),
('Frei Martinho', ARRAY['25']),
('Gado Bravo', ARRAY['49']),
('Guarabira', ARRAY['10']),
('Gurinhém', ARRAY['75']),
('Gurjão', ARRAY['22']),
('Ibiara', ARRAY['41']),
('Igaracy', ARRAY['66']),
('Imaculada', ARRAY['74']),
('Ingá', ARRAY['8']),
('Itabaiana', ARRAY['6']),
('Itaporanga', ARRAY['33']),
('Itapororoca', ARRAY['60']),
('Itatuba', ARRAY['8']),
('Jacaraú', ARRAY['60']),
('Jericó', ARRAY['36']),
('João Pessoa', ARRAY['1','64','70','76','77']),
('Joca Claudino', ARRAY['53']),
('Juarez Távora', ARRAY['9']),
('Juazeirinho', ARRAY['56']),
('Junco do Seridó', ARRAY['56']),
('Juripiranga', ARRAY['44']),
('Juru', ARRAY['74']),
('Lagoa', ARRAY['31']),
('Lagoa de Dentro', ARRAY['60']),
('Lagoa Seca', ARRAY['13']),
('Lastro', ARRAY['63']),
('Livramento', ARRAY['27']),
('Logradouro', ARRAY['14']),
('Lucena', ARRAY['2']),
('Mãe D''Água', ARRAY['30']),
('Malta', ARRAY['51']),
('Mamanguape', ARRAY['7']),
('Manaíra', ARRAY['34']),
('Marcação', ARRAY['55']),
('Mari', ARRAY['4']),
('Marizópolis', ARRAY['35']),
('Massaranduba', ARRAY['16']),
('Mataraca', ARRAY['7']),
('Matinhas', ARRAY['13']),
('Mato Grosso', ARRAY['36']),
('Maturéia', ARRAY['30']),
('Mogeiro', ARRAY['6']),
('Montadas', ARRAY['50']),
('Monte Horebe', ARRAY['40']),
('Monteiro', ARRAY['29']),
('Mulungu', ARRAY['75']),
('Natuba', '{}'),
('Nazarezinho', ARRAY['63']),
('Nova Floresta', ARRAY['24']),
('Nova Olinda', ARRAY['42']),
('Nova Palmeira', ARRAY['25']),
('Olho D''Água', ARRAY['66']),
('Olivedos', ARRAY['23']),
('Ouro Velho', ARRAY['43']),
('Parari', ARRAY['58']),
('Passagem', ARRAY['65']),
('Patos', ARRAY['28']),
('Paulista', ARRAY['69']),
('Pedra Branca', ARRAY['42']),
('Pedra Lavrada', ARRAY['25']),
('Pedras de Fogo', ARRAY['44']),
('Pedro Régis', ARRAY['60']),
('Piancó', ARRAY['32']),
('Picuí', ARRAY['25']),
('Pilar', ARRAY['44']),
('Pilões', ARRAY['11']),
('Pilõezinhos', ARRAY['47']),
('Pirpirituba', ARRAY['47']),
('Pitimbu', ARRAY['73']),
('Pocinhos', ARRAY['50']),
('Poço Dantas', ARRAY['53']),
('Poço de José de Moura', ARRAY['37']),
('Pombal', ARRAY['31']),
('Prata', ARRAY['43']),
('Princesa Isabel', ARRAY['34']),
('Puxinanã', ARRAY['50']),
('Queimadas', ARRAY['59']),
('Quixaba', ARRAY['28']),
('Remígio', ARRAY['67']),
('Riachão', ARRAY['20']),
('Riachão do Bacamarte', ARRAY['8']),
('Riachão do Poço', ARRAY['4']),
('Riacho de Santo Antônio', ARRAY['62']),
('Riacho dos Cavalos', ARRAY['38']),
('Rio Tinto', ARRAY['55']),
('Salgadinho', ARRAY['65']),
('Salgado de São Félix', ARRAY['6']),
('Santa Cecília', ARRAY['18']),
('Santa Cruz', ARRAY['63']),
('Santa Helena', ARRAY['37']),
('Santa Inês', ARRAY['41']),
('Santa Luzia', ARRAY['26']),
('Santa Rita', ARRAY['2','3']),
('Santa Terezinha', ARRAY['65']),
('Santana de Mangueira', ARRAY['41']),
('Santana dos Garrotes', ARRAY['66']),
('Santo André', ARRAY['56']),
('São Bentinho', ARRAY['51']),
('São Bento', ARRAY['69']),
('São Domingos', ARRAY['31']),
('São Domingos do Cariri', ARRAY['62']),
('São Francisco', ARRAY['63']),
('São João do Cariri', ARRAY['22']),
('São João do Rio do Peixe', ARRAY['37']),
('São João do Tigre', ARRAY['29']),
('São José da Lagoa Tapada', ARRAY['52']),
('São José de Caiana', ARRAY['33']),
('São José de Espinharas', ARRAY['51']),
('São José de Piranhas', ARRAY['40']),
('São José de Princesa', ARRAY['34']),
('São José do Bonfim', ARRAY['65']),
('São José do Brejo do Cruz', ARRAY['38']),
('São José do Sabugi', ARRAY['26']),
('São José dos Cordeiros', ARRAY['58']),
('São José dos Ramos', ARRAY['6']),
('São Mamede', ARRAY['26']),
('São Miguel de Taipu', ARRAY['44']),
('São Sebastião de Lagoa de Roça', ARRAY['19']),
('São Sebastião do Umbuzeiro', ARRAY['29']),
('São Vicente do Seridó', ARRAY['23']),
('Sapé', ARRAY['4']),
('Serra Branca', ARRAY['58']),
('Serra da Raiz', ARRAY['47']),
('Serra Grande', ARRAY['33']),
('Serra Redonda', ARRAY['72']),
('Serraria', ARRAY['11']),
('Sertãozinho', ARRAY['47']),
('Sobrado', ARRAY['4']),
('Solânea', ARRAY['48']),
('Soledade', ARRAY['23']),
('Sossêgo', ARRAY['24']),
('Sousa', ARRAY['35']),
('Sumé', ARRAY['43']),
('Tacima', ARRAY['20']),
('Taperoá', ARRAY['27']),
('Tavares', ARRAY['34']),
('Teixeira', ARRAY['30']),
('Tenório', ARRAY['56']),
('Triunfo', ARRAY['37']),
('Uiraúna', ARRAY['53']),
('Umbuzeiro', ARRAY['18']),
('Várzea', ARRAY['26']),
('Vieirópolis', ARRAY['53']),
('Vista Serrana', ARRAY['51']),
('Zabelê', ARRAY['29'])
on conflict (municipio) do update set
  zonas = excluded.zonas,
  updated_at = now();
